services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      # accept the EULA
      EULA: "TRUE" 
      TYPE: "Vanilla"

      #Server properties
      MEMORY: "20G"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON	: "FALSE"
      DIFFICULTY: "hard"
      MOTD: "Minecreaft Hardcore Survival"
      HARDCORE: "TRUE"
      ICON: "https://st2.depositphotos.com/4027737/9193/i/950/depositphotos_91939828-stock-photo-funny-rhesus-monkey-with-tongue.jpg"
      OVERRIDE_ICON: "TRUE"
      ENABLE_COMMAND_BLOCK: "FALSE"
      SERVER_NAME: "Gorila server"
      ENABLE_ROLLING_LOGS: "TRUE"

      # World properties
      VIEW_DISTANCE: "20"
      SIMULATION_DISTANCE: "20"

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./survival_hardcore/data:/data
    restart: unless-stopped

networks:
  default:
    name: data-plataform
    external: true