services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGE_VERSION: "47.4.0"
      PAPER_CHANNEL: experimental
      MEMORY: "16G"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON	: "FALSE"
      DIFFICULTY: "hard"
      MOTD: "8======D"
      HARDCORE: "TRUE"
      ICON: "https://st2.depositphotos.com/4027737/9193/i/950/depositphotos_91939828-stock-photo-funny-rhesus-monkey-with-tongue.jpg"
      OVERRIDE_ICON: "TRUE"
      ENABLE_COMMAND_BLOCK: "FALSE"
      VIEW_DISTANCE: "12"
      SIMULATION_DISTANCE: "12"
      MODE: "survival"
      SERVER_NAME: "Gorila server"
      VERSION: "1.20.1"
      GENERIC_PACK: "/data/modpacks/MODPACK_PROS_BACANAS-1.20.1.zip"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./MODPACK_PROS_BACANAS-1.20.1.zip:/data/modpacks/MODPACK_PROS_BACANAS-1.20.1.zip
    restart: unless-stopped

networks:
  default:
    name: data-plataform
    external: true